import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Generator B",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{/* Top accent line */}
				<div className="fixed top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-cyan-500 to-transparent z-50" />

				{children}
			</body>
		</html>
	);
}
