import type { Metadata } from "next";
import "@fontsource/dm-sans";
import "@fontsource/dm-mono";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className="min-h-screen bg-slate-950 text-slate-100"
					style={{ fontFamily: "'DM Sans', 'IBM Plex Mono', 'Courier New', monospace",}}>
					{/* Grid noise overlay */}
					<div className="fixed inset-0 pointer-events-none opacity-[0.03]" style={{
						backgroundImage:
							"linear-gradient(rgba(6,182,212,0.5) 1px, transparent 1px), linear-gradient(90deg, rgba(6,182,212,0.5) 1px, transparent 1px)",
						backgroundSize: "40px 40px",
					}}/>

					{/* Top accent line */}
					<div className="fixed top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-cyan-500 to-transparent z-50" />

					{/* Possible Nav Here */}

					{children}
				</div>
			</body>
		</html>
	);
}
